language: ruby
cache: bundler
branches:
  only:
    - main

rvm:
  - 3.0.6
  - 3.2.2

before_script:
  - bundle exec rake db:setup

script:
  - bundle exec rake

jobs:
  include:
    - stage: lint
      rvm: 3.0.6
      name: "Lint code with standard"
      script:
        - bundle exec rake standard

deploy:
  provider: pages
  edge: true
  # dpl_version: 2.0.3.beta.4
  cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: docs
  target_branch: gh-pages
  on:
    branch: main
  before_script:
    - bundle exec rake db:setup
  script:
    - bundle exec rake
  before_deploy:
    - cp -r coverage docs
    - git add docs
    - git commit -m "Add coverage report"

stages:
  - lint
  - test # default stage
  - deploy

env:
  global:
    - SECRET_KEY=0b1edf7e6c104a79c2986bebeb07b68d6fe617d3484c4eddc7ae7623e71cad496364709e3b4e2338d1c5ad95f83a6c75c3d8c9fb8cffbe0b5b169d7cdda8be29
    - ARTIFACTS_PATHS="./coverage"
