language: ruby
rvm:
  - 2.7.5

jobs:
  include:
    - stage: lint
      name: "Lint code with standard"
      script:
        - bundle exec rake standard
    - stage: test
      name: "test"
      script:
        - bundle exec rake db:migrate RACK_ENV=test
        - bundle exec rake
