language: ruby
cache: bundler
branches:
  only:
    - main

# define jobs matrix run on test stage
rvm:
  - 2.7.5
  - 3.2.2

jobs:
  include:
    - stage: lint
      rvm: 2.7.5
      name: "Lint code with standard"
      script:
        - bundle exec rake standard

stages:
  - lint
  - test # default stage
