development:
  adapter: "sqlite3"
  database: "db/development.sqlite3"

test:
  adapter: "sqlite3"
  database: ENV['DB_LOCATION'] || "db/test.sqlite3"
  timeout: 500

production:
  adapter: "sqlite3"
  database: "db/production.sqlite3"
